server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth_DB
    username: postgres
    password: 2001
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    user:
      name: testuser  # For basic auth in dev
      password: testpass

app:
  jwtSecret: africahr-dev-secret-key-1234567890
  jwtExpirationMs: 86400000 # 24 hours

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api/v3/api-docs
    config-url: /api/v3/api-docs/swagger-config
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match: /api/**

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.africahr.auth: DEBUG
  file:
    name: logs/auth-service-dev.log
    path: ./logs
    max-history: 30
    max-size: 10MB